helpcrunch/helpcrunch-symfony

- src/Form/HelpcrunchType.php
- src/Traits/FormTrait.php
https://helpcrunch.atlassian.net/browse/HC-2737
> HC-2737 Organizations service #3

- src/Controller/HelpcrunchController.php
- src/Service/RedisService.php
https://helpcrunch.atlassian.net/browse/HC-3274
> HC-3274 Move organization between servers

- src/Controller/HelpcrunchController.php
https://helpcrunch.atlassian.net/browse/HC-3266
> HC-3266 Fully move billing to organizations service

- src/Controller/HelpcrunchController.php
- src/Service/ApiRequestService.php
- src/Service/RedisService.php
https://helpcrunch.atlassian.net/browse/HC-3570
> HC-3570 Knowledge base templates

- src/Helper/CdnHelper.php
https://helpcrunch.atlassian.net/browse/HC-3637
> HC-3637 Added CDN Helper

- src/Controller/HelpcrunchController.php
https://helpcrunch.atlassian.net/browse/HC-3637
> HC-3637 Bulk update support

- composer.json
- src/ContainerHelper.php
- src/Validator/Constraints/UniqueValue.php
- src/Validator/Constraints/UniqueValueValidator.php
https://helpcrunch.atlassian.net/browse/HC-3830
> HC-3830 Validation message in registration

- src/Validator/Validator.php
https://helpcrunch.atlassian.net/browse/HC-3911
> HC-3911 Status sync organization<->tariffs doesn't work

- src/Response/SuccessResponse.php
https://helpcrunch.atlassian.net/browse/HC-3987
Разрешать сериализацию null можно с помощью файлов [конфигурации](https://jmsyst.com/bundles/JMSSerializerBundle/master/configuration) или с помощью метода setSerializeNull(true).
Я попробовал добавить настройки в config/packages/jms_serializer.yaml, config/packages/dev/jms_serializer.yaml и config/packages/prod/jms_serializer.yaml проекта knowledgebase. Нигде это не возымело успеха. Поэтому я добавил вызов метода напрямую сюда.
Можно сделать настройку в .env или в том же файле jms_serializer и устанавливать bool значение по тому, что мы найдем в файлах конфигурации.
> HC-3987 KB API Change serialization strategy

- src/Service/RequestService.php
- src/Service/RequestService/ApiRequestService.php
- src/Service/RequestService/KnowledgeBaseRequestService.php
https://helpcrunch.atlassian.net/browse/HC-4037
> HC-4037 KB Server Transfer

- composer.json
- src/Entity/HelpcrunchEntity.php
- src/Response/EntitiesBatchResponse.php
- src/Response/EntityResponse.php
- src/Response/SuccessResponse.php
- src/Traits/JsonSerializerTrait.php
https://helpcrunch.atlassian.net/browse/HC-3700
> HC-3700 KB Socket update: Backend

- src/Service/RequestService/KnowledgeBaseApiRequestService.php
https://helpcrunch.atlassian.net/browse/HC-4143
Для установки домена через .env
> HC-4143 Stats for KB

- src/Service/RequestService/KnowledgeBaseApiRequestService.php
https://helpcrunch.atlassian.net/browse/HC-4143
Рано смерджил
> HC-4143 Stats for KB | Remove knowledge base request service

- src/Entity/DateTimeFilteredInterface.php
- src/EventListener/DateTimeListener.php
- src/Validator/Validator.php
https://helpcrunch.atlassian.net/browse/HC-4238
> HC-4238 Ignore or format Created/Updated At on Knowledge Base API

- src/Exception/EntityRelationException.php
- src/Response/InnerErrorCodes.php
> HC-4036 KB Views -> Viewers (Back-end)

- src/EventListener/HelpcrunchApiExceptionListener.php
https://helpcrunch.atlassian.net/browse/HC-4171
> HC-4171 Separate stage into two VMs for transfer testing

- src/Helper/FormatterHelper.php
https://helpcrunch.atlassian.net/browse/HC-4402
> HC-4402 Add special symbols to search by messages (KB agent)

- src/Service/RequestService.php
- src/Service/RequestService/OrganizationsRequestService.php
https://helpcrunch.atlassian.net/browse/HC-4578
> HC-4578 Optimize knowledge base's reports generating

- src/Authentication.php
- src/Service/TokenAuthService/ProductAuthService.php
- src/Service/TokenAuthServiceFactory.php
https://helpcrunch.atlassian.net/browse/HC-4606
> HC-4606 [B] KB integration into widget

- src/Helper/FormatterHelper.php
https://helpcrunch.atlassian.net/browse/HC-4621
> HC-4621 Cyrillic & Chinese search does not work in KB

- src/Validator/Validator.php
https://helpcrunch.atlassian.net/browse/HC-4673
Сохранять сущность со связями не получилось.
> HC-4673 Helpcrunch Validator upgrade

- src/Service/RequestService/NewApiRequestService.php
- src/Traits/HelpcrunchServicesTrait.php
https://helpcrunch.atlassian.net/browse/HC-4466
> HC-4466 Registration updates

- composer.json
- src/Helper/DefaultEntities/AbstractDefaultEntitiesHelper.php
- src/Traits/HelpcrunchServicesTrait.php
https://helpcrunch.atlassian.net/browse/HC-4997
> HC-4997 [B] Change broadcast chats storage scheme

- src/EventSubscriber/TokenAuthSubscriber.php
- src/Helper/SDKHelper.php
https://helpcrunch.atlassian.net/browse/HC-5817
> HC-5817 Chats list response for mobile apps

- src/Annotation/AuthSpecification/ApplicationAuthSpecification.php
- src/Authentication.php
https://helpcrunch.atlassian.net/browse/HC-5287
> HC-5287 [B] Departments in widget

- src/EventSubscriber/TokenAuthSubscriber.php
https://helpcrunch.atlassian.net/browse/HC-5799
> HC-5799 Integration with onetool

- composer.json
- src/Service/TokenAuthService/JWTAuthService.php
* Implemented a new logic of customer authentication
https://helpcrunch.atlassian.net/browse/HC-6587
> HC-6587: [B] Agent JWT Authorization
